#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import sys

sys.path.append('/home/wny/fd_sys/mysite/')

os.environ['DJANGO_SETTINGS_MODULE'] ='mysite.settings'

from django.core.management import setup_environ

from mysite import settings

from fault_data.models import *


#python manage.py syncdb

#我是分割线

#FaultMode.objects.all().delete()


#故障原因 开始
'''
p=FaultCause(FaultCauseID=23,FaultCause="运行参数错误",FaultCauseDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=24,FaultCause="节点电机故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=25,FaultCause="节点索长超限",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=26,FaultCause="节点温度超限",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=27,FaultCause="节点索力超限",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=28,FaultCause="节点未开启上传功能",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=29,FaultCause="节点网线断开",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=30,FaultCause="区域控制器未连接节点",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=31,FaultCause="反射面温度过高",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=32,FaultCause="刚索断裂",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=32,FaultCause="刚索腐蚀损坏",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=32,FaultCause="线缆断裂",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=38,FaultCause="节点未上电",FaultCauseDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=39,FaultCause="节点网线断开",FaultCauseDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
p=FaultCause(FaultCauseID=39,FaultCause="区域控制器未连接节点",FaultCauseDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0,MaintenanceSuggestions="test2")
p.save()
'''
#故障原因 结束


# 故障模式 开始
#p=FaultMode(FaultModeID=0,FaultMode="NULL",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
#p.save()
p=FaultMode(FaultModeID=1,FaultMode="反射面故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=2,FaultMode="抛物面成型失败",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=3,FaultMode="命令执行失败",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=4,FaultMode="照明区域错误",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=5,FaultMode="节点运行超时",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=6,FaultMode="节点没有反馈",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=7,FaultMode="反射面面板故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=8,FaultMode="钢索故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=9,FaultMode="线缆故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=10,FaultMode="节点连接失败",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=11,FaultMode="节点不转动",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()


p=FaultMode(FaultModeID=14,FaultMode="馈源支撑故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=15,FaultMode="馈源舱未动",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=16,FaultMode="馈源舱未达到指定位置",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=17,FaultMode="馈源舱刚锁系统故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=18,FaultMode="馈源舱测量仪器故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=19,FaultMode="一次支撑未到位",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=20,FaultMode="二次支撑未到位",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=21,FaultMode="索故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=22,FaultMode="电机故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=23,FaultMode="馈源舱故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=24,FaultMode="工控机故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=25,FaultMode="Stewart平台故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=26,FaultMode="A-B转台故障",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()

p=FaultMode(FaultModeID=27,FaultMode="命令无法发送",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=28,FaultMode="执行器连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=29,FaultMode="子系统代理连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()

p=FaultMode(FaultModeID=32,FaultMode="ARSA连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=33,FaultMode="CSSA连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=34,FaultMode="ARS子系统连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=35,FaultMode="CSS子系统连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()

p=FaultMode(FaultModeID=40,FaultMode="MASTER连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=41,FaultMode="区域控制器连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=42,FaultMode="节点连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=43,FaultMode="索塔连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=44,FaultMode="工控机连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
p=FaultMode(FaultModeID=45,FaultMode="馈源连接异常",FaultDescription="test",DetectionMethod=1,ManualDetectionMethodID="test",FunctionID="test",Priority=1,LogicalRelationship=0)
p.save()
# 故障模式 结束

#故障关系 开始
p=FaultModeRelation(HighLevelFaultModeID=0,FaultModeID=1,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=1,FaultModeID=2,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=1,FaultModeID=3,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=2,FaultModeID=4,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=2,FaultModeID=5,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=2,FaultModeID=6,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=2,FaultModeID=7,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=2,FaultModeID=8,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=2,FaultModeID=9,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=3,FaultModeID=10,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=3,FaultModeID=11,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=3,FaultModeID=5,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=3,FaultModeID=6,LogicalRelationship=0)
p.save()
#
p=FaultModeRelation(HighLevelFaultModeID=0,FaultModeID=14,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=14,FaultModeID=15,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=14,FaultModeID=16,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=15,FaultModeID=17,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=15,FaultModeID=18,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=16,FaultModeID=19,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=16,FaultModeID=20,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=16,FaultModeID=18,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=19,FaultModeID=21,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=19,FaultModeID=22,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=20,FaultModeID=23,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=20,FaultModeID=24,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=23,FaultModeID=25,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=23,FaultModeID=26,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=25,FaultModeID=22,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=26,FaultModeID=22,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=0,FaultModeID=27,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=27,FaultModeID=28,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=27,FaultModeID=29,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=29,FaultModeID=32,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=29,FaultModeID=33,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=29,FaultModeID=34,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=29,FaultModeID=35,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=32,FaultModeID=40,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=32,FaultModeID=41,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=41,FaultModeID=42,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=35,FaultModeID=43,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=35,FaultModeID=44,LogicalRelationship=0)
p.save()
p=FaultModeRelation(HighLevelFaultModeID=44,FaultModeID=45,LogicalRelationship=0)
p.save()
#故障关系 结束
